package pojo;
// Generated Jul 3, 2021 10:54:01 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private Integer feedbackId;
     private int feedbackUserId;
     private Date feedbackDate;
     private String feedbackTitle;
     private String feedbackNote;
     private String feedbackState;

    public Feedback() {
    }

    public Feedback(int feedbackUserId, Date feedbackDate, String feedbackTitle, String feedbackNote, String feedbackState) {
       this.feedbackUserId = feedbackUserId;
       this.feedbackDate = feedbackDate;
       this.feedbackTitle = feedbackTitle;
       this.feedbackNote = feedbackNote;
       this.feedbackState = feedbackState;
    }
   
    public Integer getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }
    public int getFeedbackUserId() {
        return this.feedbackUserId;
    }
    
    public void setFeedbackUserId(int feedbackUserId) {
        this.feedbackUserId = feedbackUserId;
    }
    public Date getFeedbackDate() {
        return this.feedbackDate;
    }
    
    public void setFeedbackDate(Date feedbackDate) {
        this.feedbackDate = feedbackDate;
    }
    public String getFeedbackTitle() {
        return this.feedbackTitle;
    }
    
    public void setFeedbackTitle(String feedbackTitle) {
        this.feedbackTitle = feedbackTitle;
    }
    public String getFeedbackNote() {
        return this.feedbackNote;
    }
    
    public void setFeedbackNote(String feedbackNote) {
        this.feedbackNote = feedbackNote;
    }
    public String getFeedbackState() {
        return this.feedbackState;
    }
    
    public void setFeedbackState(String feedbackState) {
        this.feedbackState = feedbackState;
    }




}


