package pojo;
// Generated Jul 3, 2021 10:54:01 AM by Hibernate Tools 4.3.1



/**
 * Neworder generated by hbm2java
 */
public class Neworder  implements java.io.Serializable {


     private Integer neworderId;
     private int neworderItemId;
     private int neworderQuntity;
     private String neworderDate;
     private String neworderTime;
     private int neworderUserId;
     private String neworderNewAddres;
     private String neworderState;
     private int neworderDelverId;

    public Neworder() {
    }

    public Neworder(int neworderItemId, int neworderQuntity, String neworderDate, String neworderTime, int neworderUserId, String neworderNewAddres, String neworderState, int neworderDelverId) {
       this.neworderItemId = neworderItemId;
       this.neworderQuntity = neworderQuntity;
       this.neworderDate = neworderDate;
       this.neworderTime = neworderTime;
       this.neworderUserId = neworderUserId;
       this.neworderNewAddres = neworderNewAddres;
       this.neworderState = neworderState;
       this.neworderDelverId = neworderDelverId;
    }
   
    public Integer getNeworderId() {
        return this.neworderId;
    }
    
    public void setNeworderId(Integer neworderId) {
        this.neworderId = neworderId;
    }
    public int getNeworderItemId() {
        return this.neworderItemId;
    }
    
    public void setNeworderItemId(int neworderItemId) {
        this.neworderItemId = neworderItemId;
    }
    public int getNeworderQuntity() {
        return this.neworderQuntity;
    }
    
    public void setNeworderQuntity(int neworderQuntity) {
        this.neworderQuntity = neworderQuntity;
    }
    public String getNeworderDate() {
        return this.neworderDate;
    }
    
    public void setNeworderDate(String neworderDate) {
        this.neworderDate = neworderDate;
    }
    public String getNeworderTime() {
        return this.neworderTime;
    }
    
    public void setNeworderTime(String neworderTime) {
        this.neworderTime = neworderTime;
    }
    public int getNeworderUserId() {
        return this.neworderUserId;
    }
    
    public void setNeworderUserId(int neworderUserId) {
        this.neworderUserId = neworderUserId;
    }
    public String getNeworderNewAddres() {
        return this.neworderNewAddres;
    }
    
    public void setNeworderNewAddres(String neworderNewAddres) {
        this.neworderNewAddres = neworderNewAddres;
    }
    public String getNeworderState() {
        return this.neworderState;
    }
    
    public void setNeworderState(String neworderState) {
        this.neworderState = neworderState;
    }
    public int getNeworderDelverId() {
        return this.neworderDelverId;
    }
    
    public void setNeworderDelverId(int neworderDelverId) {
        this.neworderDelverId = neworderDelverId;
    }




}


