package pojo;
// Generated Jun 15, 2021 9:09:56 AM by Hibernate Tools 4.3.1



/**
 * Notify generated by hbm2java
 */
public class Notify  implements java.io.Serializable {


     private Integer notifyId;
     private int notifyUserId;
     private int notifySendUserId;
     private String notifyTital;
     private String notifyNote;
     private String notifyState;

    public Notify() {
    }

    public Notify(int notifyUserId, int notifySendUserId, String notifyTital, String notifyNote, String notifyState) {
       this.notifyUserId = notifyUserId;
       this.notifySendUserId = notifySendUserId;
       this.notifyTital = notifyTital;
       this.notifyNote = notifyNote;
       this.notifyState = notifyState;
    }
   
    public Integer getNotifyId() {
        return this.notifyId;
    }
    
    public void setNotifyId(Integer notifyId) {
        this.notifyId = notifyId;
    }
    public int getNotifyUserId() {
        return this.notifyUserId;
    }
    
    public void setNotifyUserId(int notifyUserId) {
        this.notifyUserId = notifyUserId;
    }
    public int getNotifySendUserId() {
        return this.notifySendUserId;
    }
    
    public void setNotifySendUserId(int notifySendUserId) {
        this.notifySendUserId = notifySendUserId;
    }
    public String getNotifyTital() {
        return this.notifyTital;
    }
    
    public void setNotifyTital(String notifyTital) {
        this.notifyTital = notifyTital;
    }
    public String getNotifyNote() {
        return this.notifyNote;
    }
    
    public void setNotifyNote(String notifyNote) {
        this.notifyNote = notifyNote;
    }
    public String getNotifyState() {
        return this.notifyState;
    }
    
    public void setNotifyState(String notifyState) {
        this.notifyState = notifyState;
    }




}


