package pojo;
// Generated Jul 3, 2021 10:54:01 AM by Hibernate Tools 4.3.1



/**
 * Reglist generated by hbm2java
 */
public class Reglist  implements java.io.Serializable {


     private String reglistRgId;
     private String reglistName;
     private String reglistAddress;
     private String reglistState;

    public Reglist() {
    }

    public Reglist(String reglistRgId, String reglistName, String reglistAddress, String reglistState) {
       this.reglistRgId = reglistRgId;
       this.reglistName = reglistName;
       this.reglistAddress = reglistAddress;
       this.reglistState = reglistState;
    }
   
    public String getReglistRgId() {
        return this.reglistRgId;
    }
    
    public void setReglistRgId(String reglistRgId) {
        this.reglistRgId = reglistRgId;
    }
    public String getReglistName() {
        return this.reglistName;
    }
    
    public void setReglistName(String reglistName) {
        this.reglistName = reglistName;
    }
    public String getReglistAddress() {
        return this.reglistAddress;
    }
    
    public void setReglistAddress(String reglistAddress) {
        this.reglistAddress = reglistAddress;
    }
    public String getReglistState() {
        return this.reglistState;
    }
    
    public void setReglistState(String reglistState) {
        this.reglistState = reglistState;
    }




}


