/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.mysql.jdbc.CallableStatement;
import java.sql.ResultSet;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import sesion.HibernateUtil;

/**
 *
 * @author G I U S Chamika
 */
public class addnoty extends javax.swing.JInternalFrame {

    /**
     * Creates new form adhome
     */
     String userid=null;
     int loguser;
    public addnoty() {
        initComponents();
        
        loguser=Adminlog.adminLlogid;
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
        
        
        
        
        Session session=null;
            session=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> order=new AtomicReference<>();
            session.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getalluserdata()}")){
                    cst.execute();
                    order.set(cst.getResultSet());
                    try(ResultSet rs =cst.getResultSet()){
                        while(rs.next()){
                            String reguser = rs.getString("user_reg");
                            String nameuser = rs.getString("user_full_name");
                            String stateuser = rs.getString("user_state");
                            String iduser = rs.getString("user_id");
                            
                            
                            
                            String tbData[] = {reguser, nameuser, stateuser, iduser};
                            DefaultTableModel tblm = (DefaultTableModel) jTable62.getModel();
                            tblm.addRow(tbData);
                           
                        }
                    }
                }
            });
            
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable62 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        fnamer3 = new javax.swing.JLabel();
        fnamer4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 102));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(867, 526));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable62.setBackground(new java.awt.Color(0, 204, 204));
        jTable62.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Reg", "User Name", "User State", "isuser"
            }
        ));
        jTable62.setGridColor(new java.awt.Color(0, 204, 204));
        jTable62.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jTable62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable62MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable62);
        if (jTable62.getColumnModel().getColumnCount() > 0) {
            jTable62.getColumnModel().getColumn(2).setMinWidth(100);
            jTable62.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable62.getColumnModel().getColumn(3).setMinWidth(0);
            jTable62.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable62.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 831, 150));

        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setSelectionColor(new java.awt.Color(0, 153, 153));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 540, 30));

        fnamer3.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        fnamer3.setText("Title :");
        fnamer3.setFocusable(false);
        fnamer3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fnamer3.setIconTextGap(2);
        fnamer3.setInheritsPopupMenu(false);
        jPanel1.add(fnamer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 90, 30));

        fnamer4.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        fnamer4.setText(" Note :");
        fnamer4.setFocusable(false);
        fnamer4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fnamer4.setIconTextGap(2);
        fnamer4.setInheritsPopupMenu(false);
        jPanel1.add(fnamer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 90, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setSelectionColor(new java.awt.Color(0, 153, 153));
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 540, 150));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/submit.png"))); // NOI18N
        jLabel15.setText("All User");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 80, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/submit.png"))); // NOI18N
        jLabel16.setText("This User");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 320, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
    
        String tital =jTextField2.getText();
        String noteonty = jTextArea1.getText();
        
            if(!tital.isEmpty() && !noteonty.isEmpty()){
                
                
                Session session=null;
                session=HibernateUtil.getSessionFactory().openSession();
                final AtomicReference<ResultSet> order=new AtomicReference<>();
                session.doWork(connection->{
                    try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call addnewnoty(?,?,?,?)}")){
                        cst.setInt(1, 0);
                        cst.setInt(2, loguser);
                        cst.setString(3, tital);
                        cst.setString(4, noteonty);
                        cst.execute();
                        
                    }
                });
                
                jTextField2.setText("");
                jTextArea1.setText("");
                jLabel9.setForeground(new java.awt.Color(0, 204, 51));
                jLabel9.setText("Successful add note");
                
            }else{
                jLabel9.setForeground(new java.awt.Color(255, 0, 0));
                jLabel9.setText("Please fill All Fields !");
            }
        
     
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        
        String tital =jTextField2.getText();
        String noteonty = jTextArea1.getText();
        if(userid!=null){
            if(!tital.isEmpty() && !noteonty.isEmpty()){
                int userrid = Integer.parseInt(userid);
                
                Session session=null;
                session=HibernateUtil.getSessionFactory().openSession();
                final AtomicReference<ResultSet> order=new AtomicReference<>();
                session.doWork(connection->{
                    try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call addnewnoty(?,?,?,?)}")){
                        cst.setInt(1, userrid);
                        cst.setInt(2, loguser);
                        cst.setString(3, tital);
                        cst.setString(4, noteonty);
                        cst.execute();
                        
                    }
                });
                userid=null;
                jTextField2.setText("");
                jTextArea1.setText("");
                jLabel9.setForeground(new java.awt.Color(0, 204, 51));
                jLabel9.setText("Successful add note");
                
            }else{
                jLabel9.setForeground(new java.awt.Color(255, 0, 0));
                jLabel9.setText("Please fill All Fields !");
            }
        }else{
            jLabel9.setForeground(new java.awt.Color(255, 0, 0));
            jLabel9.setText("Plese Select User !");
        }
        
        
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jTable62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable62MouseClicked
         DefaultTableModel dmodel = (DefaultTableModel) jTable62.getModel();
        int selectindex = jTable62.getSelectedRow();

        userid = dmodel.getValueAt(selectindex, 3).toString();
        
        
        
    }//GEN-LAST:event_jTable62MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eroorlod56;
    private javax.swing.JLabel eroorlod57;
    private javax.swing.JLabel fnamer3;
    private javax.swing.JLabel fnamer4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable62;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
