/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.mysql.jdbc.CallableStatement;
import java.sql.ResultSet;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import sesion.HibernateUtil;

/**
 *
 * @author G I U S Chamika
 */
public class addsummary extends javax.swing.JInternalFrame {

    /**
     * Creates new form adhome
     */
    public addsummary() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
        
        
        Session session=null;
            session=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> order=new AtomicReference<>();
            session.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getitemdaly(?)}")){
                    cst.setString(1, "All");
                    cst.execute();
                    order.set(cst.getResultSet());
                    try(ResultSet rs =cst.getResultSet()){
                        while(rs.next()){
                            
                            String name = rs.getString("item_name");
                            String catagory=rs.getString("item_catagory");
                            String price=rs.getString("item_price");
                            String quntity=rs.getString("sold qun");
                            String total=rs.getString("total");
                            String datethis=rs.getString("neworder_date");
                            
                            
                            String tbData[] = {name, catagory, price, quntity, total, datethis};
                            DefaultTableModel tblm = (DefaultTableModel) jTable62.getModel();
                            tblm.addRow(tbData);
                           
                        }
                    }
                }
            });
            
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable62 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 102));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(867, 526));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable62.setBackground(new java.awt.Color(0, 204, 204));
        jTable62.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Catagory", "Price", "Quantity", "Total", "Date"
            }
        ));
        jTable62.setGridColor(new java.awt.Color(0, 204, 204));
        jTable62.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(jTable62);
        if (jTable62.getColumnModel().getColumnCount() > 0) {
            jTable62.getColumnModel().getColumn(2).setMinWidth(100);
            jTable62.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable62.getColumnModel().getColumn(3).setMinWidth(100);
            jTable62.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable62.getColumnModel().getColumn(4).setMinWidth(100);
            jTable62.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 831, 380));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Month By");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 50, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("All  /");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 30, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Day By /");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        //       jTable62.setModel(new DefaultTableModel(null,new String[]{"Item Name", "Item Catagory", "Price", "Quntity", "Total"}));
        jTable62.setBackground(new java.awt.Color(0, 204, 204));
        jTable62.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Catagory", "Price", "Quntity", "Total", "Date"
            }
        ));
        jTable62.setGridColor(new java.awt.Color(0, 204, 204));
        jTable62.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(jTable62);
        if (jTable62.getColumnModel().getColumnCount() > 0) {
            jTable62.getColumnModel().getColumn(2).setMinWidth(100);
            jTable62.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable62.getColumnModel().getColumn(3).setMinWidth(100);
            jTable62.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable62.getColumnModel().getColumn(4).setMinWidth(100);
            jTable62.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        Session session=null;
            session=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> order=new AtomicReference<>();
            session.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getitemdaly(?)}")){
                    cst.setString(1, "All");
                    cst.execute();
                    order.set(cst.getResultSet());
                    try(ResultSet rs =cst.getResultSet()){
                        while(rs.next()){
                            
                            String name = rs.getString("item_name");
                            String catagory=rs.getString("item_catagory");
                            String price=rs.getString("item_price");
                            String quntity=rs.getString("sold qun");
                            String total=rs.getString("total");
                            String datethis=rs.getString("neworder_date");
                            
                            
                            String tbData[] = {name, catagory, price, quntity, total, datethis};
                            DefaultTableModel tblm = (DefaultTableModel) jTable62.getModel();
                            tblm.addRow(tbData);
                           
                        }
                    }
                }
            });
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        jTable62.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Catagory", "Price", "Quntity", "Total"
            }
        ));
        if (jTable62.getColumnModel().getColumnCount() > 0) {
            jTable62.getColumnModel().getColumn(2).setMinWidth(100);
            jTable62.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable62.getColumnModel().getColumn(3).setMinWidth(100);
            jTable62.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable62.getColumnModel().getColumn(4).setMinWidth(100);
            jTable62.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(4).setMaxWidth(100);
        }
        Session session2=null;
        session2=HibernateUtil.getSessionFactory().openSession();
        final AtomicReference<ResultSet> order=new AtomicReference<>();
        session2.doWork(connection->{
            try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getitemdaly(?)}")){
                cst.setString(1, "mon");
                cst.execute();
                order.set(cst.getResultSet());
                try(ResultSet rs =cst.getResultSet()){
                    while(rs.next()){

                        String name = rs.getString("item_name");
                        String catagory=rs.getString("item_catagory");
                        String price=rs.getString("item_price");
                        String quntity=rs.getString("SUM(`sold qun`)");
                        String total=rs.getString("SUM(`total`)");

                        String tbData[] = {name, catagory, price, quntity, total};
                        DefaultTableModel tblm = (DefaultTableModel) jTable62.getModel();
                        tblm.addRow(tbData);

                    }
                }
            }
        });

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        //       jTable62.setModel(new DefaultTableModel(null,new String[]{"Item Name", "Item Catagory", "Price", "Quntity", "Total"}));
        jTable62.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Catagory", "Price", "Quntity", "Total"
            }
        ));
        if (jTable62.getColumnModel().getColumnCount() > 0) {
            jTable62.getColumnModel().getColumn(2).setMinWidth(100);
            jTable62.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable62.getColumnModel().getColumn(3).setMinWidth(100);
            jTable62.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable62.getColumnModel().getColumn(4).setMinWidth(100);
            jTable62.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable62.getColumnModel().getColumn(4).setMaxWidth(100);
        }
        Session session1=null;
        session1=HibernateUtil.getSessionFactory().openSession();
        final AtomicReference<ResultSet> order=new AtomicReference<>();
        session1.doWork(connection->{
            try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getitemdaly(?)}")){
                cst.setString(1, "day");
                cst.execute();
                order.set(cst.getResultSet());
                try(ResultSet rs =cst.getResultSet()){
                    while(rs.next()){

                        String name = rs.getString("item_name");
                        String catagory=rs.getString("item_catagory");
                        String price=rs.getString("item_price");
                        String quntity=rs.getString("sold qun");
                        String total=rs.getString("total");

                        String tbData[] = {name, catagory, price, quntity, total};
                        DefaultTableModel tblm = (DefaultTableModel) jTable62.getModel();
                        tblm.addRow(tbData);

                    }
                }
            }
        });
    }//GEN-LAST:event_jLabel8MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable62;
    // End of variables declaration//GEN-END:variables
}
