/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static UI.LogReg.session;
import com.mysql.jdbc.CallableStatement;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.concurrent.atomic.AtomicReference;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import pojo.User;
import sesion.HibernateUtil;
import sesion.HibernateUtil1;

/**
 *
 * @author G I U S Chamika
 */
public class Adminlog extends javax.swing.JFrame {

    /**
     * Creates new form Adminlog
     */
    public static int adminLlogid=0;
    String userregid=null;
    static Session session=null;
    String uname=null;
    int usernameval=0;
    public Adminlog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usernamelog = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPasswordField1log = new javax.swing.JPasswordField();
        errorlog = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(78, 148, 148));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reg Id");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 140, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password?");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 90, 30));

        usernamelog.setBackground(new java.awt.Color(78, 148, 148));
        usernamelog.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        usernamelog.setForeground(new java.awt.Color(204, 204, 204));
        usernamelog.setBorder(null);
        usernamelog.setOpaque(false);
        usernamelog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamelogActionPerformed(evt);
            }
        });
        jPanel4.add(usernamelog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 410, 30));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 400, 10));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 400, 10));

        jPasswordField1log.setBackground(new java.awt.Color(78, 148, 148));
        jPasswordField1log.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1log.setBorder(null);
        jPasswordField1log.setOpaque(false);
        jPasswordField1log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1logActionPerformed(evt);
            }
        });
        jPanel4.add(jPasswordField1log, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 400, -1));

        errorlog.setBackground(new java.awt.Color(0, 204, 204));
        errorlog.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        errorlog.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(errorlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 440, 30));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 140, 30));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fogot");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 40, 30));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        jLabel14.setText("SCDveloper.com");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 90, 30));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Copyright ©2021 All rights reserved | This Design is made by ");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 330, 30));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 150, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernamelogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamelogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamelogActionPerformed

    private void jPasswordField1logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1logActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1logActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        String usarname=usernamelog.getText();
        String passwd=jPasswordField1log.getText();
        String error_note4=null;
        if(!usarname.isEmpty() && !passwd.isEmpty()){
            session=HibernateUtil.getSessionFactory().openSession();
            Transaction tx=session.beginTransaction();
            String user_sql="FROM User";
            Query user_quary=session.createQuery(user_sql);

            java.util.List <User>userList=user_quary.list();
            for(Iterator<User> userIterator=userList.iterator();userIterator.hasNext();){
                User user=userIterator.next();
                if(user.getUserReg().equals(usernamelog.getText()) && user.getUserState().equals("Admin")){
                    //encrip pwd
                    String generatedPassword = null;
                    try {

                        MessageDigest md = MessageDigest.getInstance("MD5");
                        md.update(jPasswordField1log.getText().getBytes());
                        byte[] bytes = md.digest();
                        StringBuilder sb = new StringBuilder();
                        for(int i=0; i< bytes.length ;i++)
                        {
                            sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
                        }
                        generatedPassword = sb.toString();
                    }
                    catch (NoSuchAlgorithmException e)
                    {
                        e.printStackTrace();
                    }
                    if(user.getUserPassword().equals(generatedPassword)) {
                        
                            adminLlogid = user.getUserId();
                            Session session4=null;
                                session4=HibernateUtil.getSessionFactory().openSession();
                                final AtomicReference<ResultSet> log=new AtomicReference<>();
                                session4.doWork(connection->{
                                    try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call logmaintain(?,?)}")){
                                        cst.setInt(2, adminLlogid);
                                        cst.setString(1, "log");
                                        cst.execute();
                                        
                                    }
                                });
                            this.setVisible(false);
                            new Dashadmin().setVisible(true);
                        
                            
                        
                    }else{
                        usernameval=1;
                    }
                }else{
                    usernameval=1;
                }
            }

            if(usernameval==1){
                error_note4="Wrong User Reg or Password !";
            }else{
                error_note4="";
            }

        }else{
            error_note4="Some Field/s Empty !";
        }
        errorlog.setText(error_note4);
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminlog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorlog;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1log;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField usernamelog;
    // End of variables declaration//GEN-END:variables
}
