/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.mysql.jdbc.CallableStatement;
import java.sql.ResultSet;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import sesion.HibernateUtil;

/**
 *
 * @author G I U S Chamika
 */
public class deliverwork extends javax.swing.JInternalFrame {

    /**
     * Creates new form adhome
     */
    String selectitemidu =null;
    public deliverwork() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
       Session session=null;
            session=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> order=new AtomicReference<>();
            session.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getdeliverupin(?,?,?,?)}")){
                    cst.setString(1, "All");
                    cst.setInt(2, 0);
                    cst.setString(3, "No");
                    cst.setString(4, "No");
                    cst.execute();
                    order.set(cst.getResultSet());
                    try(ResultSet rs =cst.getResultSet()){
                        while(rs.next()){
                            
                            String name = rs.getString("deliver_name");
                            String dtel = rs.getString("deliver_tel");
                            String today = rs.getString("deliver_qun_today");
                            String month = rs.getString("deliver_qun_month");
                            String deliid = rs.getString("deliver_id");

                            
                            
                            
                            String tbData[] = {name, dtel, today, month, deliid};
                            DefaultTableModel tblm = (DefaultTableModel) jTable68.getModel();
                            tblm.addRow(tbData);
                           
                        }
                    }
                }
            });
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable68 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 102));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(867, 526));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable68.setBackground(new java.awt.Color(0, 204, 204));
        jTable68.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Deliver Name", "Deliver Tel", "Today Delivery", "This Month Delivery", "del id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable68.setGridColor(new java.awt.Color(0, 204, 204));
        jTable68.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jTable68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable68MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable68);
        if (jTable68.getColumnModel().getColumnCount() > 0) {
            jTable68.getColumnModel().getColumn(4).setMinWidth(0);
            jTable68.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable68.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 840, 190));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 290, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 290, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enter2.png"))); // NOI18N
        jLabel2.setText("Update");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 90, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Update Item");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 810, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 50, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField3.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField3.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 300, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tel");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 60, 30));

        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField4.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField4.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deliup.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 830, 110));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField5.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField5.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 300, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 50, 30));

        jTextField6.setForeground(new java.awt.Color(51, 51, 51));
        jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField6.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField6.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 250, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Add New Deliver");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 810, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tel");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 60, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enter2.png"))); // NOI18N
        jLabel3.setText("Add");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 70, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deliup.png"))); // NOI18N
        jLabel6.setText("jLabel1");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 830, 110));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Catagory");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable68MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable68MouseClicked
        
        DefaultTableModel dmodel2 = (DefaultTableModel) jTable68.getModel();
       int selectindex = jTable68.getSelectedRow();
      
       selectitemidu = dmodel2.getValueAt(selectindex, 4).toString();
       jTextField3.setText(dmodel2.getValueAt(selectindex, 0).toString());
       jTextField4.setText(dmodel2.getValueAt(selectindex, 1).toString());
       
        
    }//GEN-LAST:event_jTable68MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        String telno = jTextField3.getText();
        String dliname = jTextField4.getText();
       
        if(selectitemidu!=null){
            if(!telno.isEmpty() && !dliname.isEmpty()){
                int orderid = Integer.parseInt(selectitemidu);

                Session session2=null;
                    session2=HibernateUtil.getSessionFactory().openSession();
                    final AtomicReference<ResultSet> order=new AtomicReference<>();
                    session2.doWork(connection->{
                        try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getdeliverupin(?,?,?,?)}")){
                            cst.setString(1, "Up");
                            cst.setInt(2, orderid);
                            cst.setString(4, dliname);
                            cst.setString(3, telno);
                            cst.execute();

                        }
                    });

                    jTable68.setBackground(new java.awt.Color(0, 204, 204));
                jTable68.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Deliver Name", "Deliver Tel", "Today Delivary", "This Month Delivary", "del id"
                    }
                ) {
                    boolean[] canEdit = new boolean [] {
                        true, true, true, true, false
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                jTable68.setGridColor(new java.awt.Color(0, 204, 204));
                jTable68.setSelectionBackground(new java.awt.Color(0, 102, 102));
                jTable68.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable68MouseClicked(evt);
                    }
                });

                if (jTable68.getColumnModel().getColumnCount() > 0) {
                    jTable68.getColumnModel().getColumn(4).setMinWidth(0);
                    jTable68.getColumnModel().getColumn(4).setPreferredWidth(0);
                    jTable68.getColumnModel().getColumn(4).setMaxWidth(0);
                }

                Session session=null;
                    session=HibernateUtil.getSessionFactory().openSession();
                    final AtomicReference<ResultSet> order2=new AtomicReference<>();
                    session.doWork(connection->{
                        try(CallableStatement cst2=(CallableStatement) connection.prepareCall("{call getdeliverupin(?,?,?,?)}")){
                            cst2.setString(1, "All");
                            cst2.setInt(2, 0);
                            cst2.setString(3, "No");
                            cst2.setString(4, "No");
                            cst2.execute();
                            order.set(cst2.getResultSet());
                            try(ResultSet rs2 =cst2.getResultSet()){
                                while(rs2.next()){

                                    String name = rs2.getString("deliver_name");
                                    String dtel = rs2.getString("deliver_tel");
                                    String today = rs2.getString("deliver_qun_today");
                                    String month = rs2.getString("deliver_qun_month");
                                    String deliid = rs2.getString("deliver_id");




                                    String tbData[] = {name, dtel, today, month, deliid};
                                    DefaultTableModel tblm = (DefaultTableModel) jTable68.getModel();
                                    tblm.addRow(tbData);

                                }
                            }
                        }
                    });
                    
                    selectitemidu=null;

                    jLabel15.setForeground(new java.awt.Color(0, 204, 51));
                    jLabel15.setText("Successful Update Deliver");
            }else{
                jLabel15.setForeground(new java.awt.Color(255, 0, 0));
                jLabel15.setText("Some Fields Empty !");
            }
        }else{
            jLabel15.setForeground(new java.awt.Color(255, 0, 0));
            jLabel15.setText("Please Select Item !");
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        String telno2 = jTextField5.getText();
        String dliname2 = jTextField6.getText();
       
            if(!telno2.isEmpty() && !dliname2.isEmpty()){
               
                Session session2=null;
                    session2=HibernateUtil.getSessionFactory().openSession();
                    final AtomicReference<ResultSet> order=new AtomicReference<>();
                    session2.doWork(connection->{
                        try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getdeliverupin(?,?,?,?)}")){
                            cst.setString(1, "In");
                            cst.setInt(2, 0);
                            cst.setString(4, dliname2);
                            cst.setString(3, telno2);
                            cst.execute();

                        }
                    });

                    jTable68.setBackground(new java.awt.Color(0, 204, 204));
                jTable68.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Deliver Name", "Deliver Tel", "Today Delivary", "This Month Delivary", "del id"
                    }
                ) {
                    boolean[] canEdit = new boolean [] {
                        true, true, true, true, false
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                jTable68.setGridColor(new java.awt.Color(0, 204, 204));
                jTable68.setSelectionBackground(new java.awt.Color(0, 102, 102));
                jTable68.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable68MouseClicked(evt);
                    }
                });

                if (jTable68.getColumnModel().getColumnCount() > 0) {
                    jTable68.getColumnModel().getColumn(4).setMinWidth(0);
                    jTable68.getColumnModel().getColumn(4).setPreferredWidth(0);
                    jTable68.getColumnModel().getColumn(4).setMaxWidth(0);
                }

                Session session=null;
                    session=HibernateUtil.getSessionFactory().openSession();
                    final AtomicReference<ResultSet> order2=new AtomicReference<>();
                    session.doWork(connection->{
                        try(CallableStatement cst2=(CallableStatement) connection.prepareCall("{call getdeliverupin(?,?,?,?)}")){
                            cst2.setString(1, "All");
                            cst2.setInt(2, 0);
                            cst2.setString(3, "No");
                            cst2.setString(4, "No");
                            cst2.execute();
                            order.set(cst2.getResultSet());
                            try(ResultSet rs2 =cst2.getResultSet()){
                                while(rs2.next()){

                                    String name = rs2.getString("deliver_name");
                                    String dtel = rs2.getString("deliver_tel");
                                    String today = rs2.getString("deliver_qun_today");
                                    String month = rs2.getString("deliver_qun_month");
                                    String deliid = rs2.getString("deliver_id");




                                    String tbData[] = {name, dtel, today, month, deliid};
                                    DefaultTableModel tblm = (DefaultTableModel) jTable68.getModel();
                                    tblm.addRow(tbData);

                                }
                            }
                        }
                    });

                    jLabel9.setForeground(new java.awt.Color(0, 204, 51));
                    jLabel9.setText("Successful Add Deliver");
            }else{
                jLabel9.setForeground(new java.awt.Color(255, 0, 0));
                jLabel9.setText("Some Fields Empty !");
            }
        
        
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable68;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
