/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import ClassSet.EmailSend;
import static UI.LogReg.session;
import com.mysql.jdbc.CallableStatement;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import pojo.User;
import sesion.HibernateUtil;



/**
 *
 * @author G I U S Chamika
 */
public class Myorderinner extends javax.swing.JInternalFrame {

   int loguser= LogReg.Lloguserid;
   int count =0;
   String selectorderid =null;
    public Myorderinner() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        Session session=null;
            session=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> order=new AtomicReference<>();
            session.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call billpendingdata(?)}")){
                    cst.setInt(1, loguser);
                    cst.execute();
                    order.set(cst.getResultSet());
                    try(ResultSet rs =cst.getResultSet()){
                        while(rs.next()){
                            count=count+1;
                            String id = rs.getString("neworder_id");
                            String date=rs.getString("neworder_date");
                            String food=rs.getString("item_name");
                            String quntit=rs.getString("neworder_quntity");
                            String price=rs.getString("item_price");
                            String deli=rs.getString("deliver_name");
                            String dlitel=rs.getString("deliver_tel");
                            String orserstate=rs.getString("neworder_state");
                            String countSrt=String.valueOf(count);
                            String tbData[] = {countSrt,food,date,quntit,price,deli,dlitel,id,orserstate};
                            DefaultTableModel tblm = (DefaultTableModel) jTable45.getModel();
                            tblm.addRow(tbData);
                           
                        }
                    }
                }
            });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable45 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(819, 526));
        setPreferredSize(new java.awt.Dimension(819, 526));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 223, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 480));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 255, 255));

        jTable45.setBackground(new java.awt.Color(115, 204, 204));
        jTable45.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable45.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Item", "Date", "Quantity", "Price", "Deliver", "Deliver Tel", "Ord num", "Order State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable45.setGridColor(new java.awt.Color(0, 204, 204));
        jTable45.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jTable45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable45MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable45);
        if (jTable45.getColumnModel().getColumnCount() > 0) {
            jTable45.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable45.getColumnModel().getColumn(7).setMinWidth(0);
            jTable45.getColumnModel().getColumn(7).setPreferredWidth(0);
            jTable45.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 800, 260));

        jPanel3.setBackground(new java.awt.Color(245, 223, 245));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Date ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 190, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Total ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 200, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Item ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 210, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Click Here !");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Date :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 40, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Total :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 750, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Item :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText(" Receive order");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 90, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Order?");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 40, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 0));
        jLabel11.setText("Include 04 h Order Receive");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Report ");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 60, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 750, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 750, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int Total = 0;
     int Total2 = 0;
    private void jTable45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable45MouseClicked
        
      DefaultTableModel dmodel = (DefaultTableModel) jTable45.getModel();
      int selectindex = jTable45.getSelectedRow();
      
       selectorderid = dmodel.getValueAt(selectindex, 7).toString();
       Session session2=null;
            session2=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> selordr=new AtomicReference<>();
            session2.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call selectbilldata(?)}")){
                    cst.setString(1, selectorderid);
                    cst.execute();
                    selordr.set(cst.getResultSet());
                    try(ResultSet rs =cst.getResultSet()){
                        while(rs.next()){
                            
                            jLabel3.setText(rs.getString("item_name"));
                            jLabel1.setText(rs.getString("neworder_date"));
                            int price =rs.getInt("item_price");
                            int qun =rs.getInt("neworder_quntity");
                            Total = (price * qun);
                            jLabel2.setText("Rs: "+Total+"/-");
                        }
                    }
                }
            });
    }//GEN-LAST:event_jTable45MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Session session3=null;
            session3=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> upordet=new AtomicReference<>();
            session3.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call updateorderstate(?,?)}")){
                    cst.setString(1, selectorderid);
                    cst.setString(2, "Reseve");
                    cst.execute();
                    
                }
            });
            //jLabel13.setText("Successfull Feedback We Find out You Problem");
            jLabel13.setText("Successfull Feedback ");
            jLabel7.setText("Thank You! Order Again.");
            
            
            Session session5=null;
            session5=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> selordr=new AtomicReference<>();
            session5.doWork(connection->{
                try(CallableStatement cst2=(CallableStatement) connection.prepareCall("{call selectbilldata(?)}")){
                    cst2.setString(1, selectorderid);
                    cst2.execute();
                    selordr.set(cst2.getResultSet());
                    try(ResultSet rs2 =cst2.getResultSet()){
                        while(rs2.next()){
                           String useremail =rs2.getString("user_email");
                           String nameitem=rs2.getString("item_name");
                           String daten=rs2.getString("neworder_date");
                            int price =rs2.getInt("item_price");
                            int qun =rs2.getInt("neworder_quntity");
                            Total2 = (price * qun);
                            
                            //send otp email
                            EmailSend es=new EmailSend();
                            es.SendMail("Item--> "+nameitem+" <br> Order Date--> "+daten+" <br> Total--> Rs: "+Total2+" <br> * Order is Complet! <br> <b>Thank You!<br> Order Again </b>",useremail,"Fot Canteen Online Food Ordering System Order Complete!");
                        }
                    }
                }
            });
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        Session session4=null;
            session4=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> upordet=new AtomicReference<>();
            session4.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call updateorderstate(?,?)}")){
                    cst.setString(1, selectorderid);
                    cst.setString(2, "Report");
                    cst.execute();
                    
                }
            });
            jLabel13.setText("Successfull Feedback We Find out You Problem");
//            jLabel13.setText("Successfull Feedback ");
            jLabel7.setText("Thank You! Order Again.");
            
            Session session5=null;
            session5=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> selordr=new AtomicReference<>();
            session5.doWork(connection->{
                try(CallableStatement cst2=(CallableStatement) connection.prepareCall("{call selectbilldata(?)}")){
                    cst2.setString(1, selectorderid);
                    cst2.execute();
                    selordr.set(cst2.getResultSet());
                    try(ResultSet rs2 =cst2.getResultSet()){
                        while(rs2.next()){
                           String useremail =rs2.getString("user_email");
                           String nameitem=rs2.getString("item_name");
                           String daten=rs2.getString("neworder_date");
                            int price =rs2.getInt("item_price");
                            int qun =rs2.getInt("neworder_quntity");
                            Total2 = (price * qun);
                            
                            //send otp email
                            EmailSend es=new EmailSend();
                            es.SendMail("Item--> "+nameitem+" <br> Order Date--> "+daten+" <br> Total--> Rs: "+Total2+" <br> <b>* Order is Report We Find Out You'r Problem!</b> <br> <b>Thank You!</b>",useremail,"Fot Canteen Online Food Ordering System Order Problem!");
                        }
                    }
                }
            });
    }//GEN-LAST:event_jLabel12MouseClicked
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable45;
    // End of variables declaration//GEN-END:variables
}
