/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.mysql.jdbc.CallableStatement;
import java.sql.ResultSet;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import sesion.HibernateUtil;

/**
 *
 * @author G I U S Chamika
 */
public class ordershipe extends javax.swing.JInternalFrame {

    /**
     * Creates new form adhome
     */
    String selectitemid;
    public ordershipe() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        Session session=null;
            session=HibernateUtil.getSessionFactory().openSession();
            final AtomicReference<ResultSet> order=new AtomicReference<>();
            session.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getoerdernew(?,?)}")){
                    cst.setInt(1, 0);
                    cst.setString(2, "pending");
                    cst.execute();
                    order.set(cst.getResultSet());
                    try(ResultSet rs =cst.getResultSet()){
                        while(rs.next()){
                            
                            String name = rs.getString("item_name");
                            String catagory=rs.getString("item_catagory");
                            String price=rs.getString("item_price");
                            String quntity=rs.getString("neworder_quntity");
                            String username = rs.getString("user_full_name");
                            String usertg=rs.getString("user_reg");
                            String address=rs.getString("neworder_new_addres");
                            String deliver=rs.getString("deliver_name");
                            String delitel=rs.getString("deliver_tel");
                            String orderid=rs.getString("neworder_id");
                            String adddate=rs.getString("neworder_date");
                            int totalint=(rs.getInt("item_price") * rs.getInt("neworder_quntity"));
                            String total = ""+totalint;
                            
                            
                            String tbData[] = {name, catagory, price, quntity, total, username, usertg, address, deliver, delitel, orderid, adddate};
                            DefaultTableModel tblm = (DefaultTableModel) jTable11.getModel();
                            tblm.addRow(tbData);
                           
                        }
                    }
                }
            });
            
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 102));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(867, 526));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable11.setBackground(new java.awt.Color(0, 204, 204));
        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Catagory", " Price", "Quantity", "Total", "User Name", "User Rg", "User Address", "Deliver", "Deliver Tel", "order id", "Date"
            }
        ));
        jTable11.setGridColor(new java.awt.Color(0, 204, 204));
        jTable11.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jTable11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable11MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable11);
        if (jTable11.getColumnModel().getColumnCount() > 0) {
            jTable11.getColumnModel().getColumn(2).setMinWidth(50);
            jTable11.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable11.getColumnModel().getColumn(2).setMaxWidth(50);
            jTable11.getColumnModel().getColumn(3).setMinWidth(50);
            jTable11.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable11.getColumnModel().getColumn(3).setMaxWidth(50);
            jTable11.getColumnModel().getColumn(4).setMinWidth(50);
            jTable11.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTable11.getColumnModel().getColumn(4).setMaxWidth(50);
            jTable11.getColumnModel().getColumn(6).setMinWidth(65);
            jTable11.getColumnModel().getColumn(6).setPreferredWidth(65);
            jTable11.getColumnModel().getColumn(6).setMaxWidth(65);
            jTable11.getColumnModel().getColumn(10).setMinWidth(0);
            jTable11.getColumnModel().getColumn(10).setPreferredWidth(0);
            jTable11.getColumnModel().getColumn(10).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 860, 210));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Price");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 50, 30));

        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField1.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField1.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 60, 30));

        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField2.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField2.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 220, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 50, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 51, 51));
        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField3.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField3.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 230, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Receive List");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 80, 30));

        jTextField4.setForeground(new java.awt.Color(102, 102, 102));
        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField4.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField4.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 230, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 50, 30));

        jTextField5.setForeground(new java.awt.Color(255, 0, 0));
        jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField5.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField5.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 230, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("User");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 30, 30));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 51, 51));
        jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField6.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField6.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("User Reg");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 70, 30));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 51, 51));
        jTextField7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField7.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField7.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 250, 20));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 51, 51));
        jTextField8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField8.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField8.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 220, 30));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checked_35px.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 150, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 204, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Order Conform");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 150, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addnewitem.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 160, 80));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Catagory");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 60, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("Report List");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 80, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 204));
        jLabel12.setText("Pending List");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 90, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setText("Shiped List");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 90, 30));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 51, 51));
        jTextField9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField9.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField9.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 230, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Delliver");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 50, 30));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 51, 51));
        jTextField10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jTextField10.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextField10.setSelectionColor(new java.awt.Color(0, 153, 153));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 210, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Deliver Tel");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 70, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Address");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable11MouseClicked
        
       DefaultTableModel dmodel = (DefaultTableModel) jTable11.getModel();
       int selectindex = jTable11.getSelectedRow();
      
       selectitemid = dmodel.getValueAt(selectindex, 10).toString();
       
       jTextField3.setText(dmodel.getValueAt(selectindex, 0).toString());
       jTextField4.setText(dmodel.getValueAt(selectindex, 1).toString());
       jTextField1.setText(dmodel.getValueAt(selectindex, 2).toString());
       jTextField2.setText(dmodel.getValueAt(selectindex, 3).toString());
       
       jTextField5.setText(dmodel.getValueAt(selectindex, 11).toString());
       jTextField6.setText(dmodel.getValueAt(selectindex, 5).toString());
       jTextField7.setText(dmodel.getValueAt(selectindex, 6).toString());
       jTextField8.setText(dmodel.getValueAt(selectindex, 7).toString());
       
       jTextField9.setText(dmodel.getValueAt(selectindex, 8).toString());
       jTextField10.setText(dmodel.getValueAt(selectindex, 9).toString());

        
       
        
       
        
    }//GEN-LAST:event_jTable11MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        
        if(selectitemid!=null){
                    int orderid = Integer.parseInt(selectitemid);

                    Session session4=null;
                    session4=HibernateUtil.getSessionFactory().openSession();
                    final AtomicReference<ResultSet> selordr=new AtomicReference<>();
                    session4.doWork(connection->{
                        try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getoerdernew(?,?)}")){
                            cst.setInt(1, orderid);
                            cst.setString(2, "No");
                            cst.execute();
                        }
                    });
                    
                jLabel9.setForeground(new java.awt.Color(0, 204, 51));
                jLabel9.setText("Successful order commform");
                
                jTable11.setBackground(new java.awt.Color(0, 204, 204));
                jTable11.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Item Name", "Item Catagory", " Price", "Quntity", "Total", "User Name", "User Rg", "User Address", "Deliver", "Deliver Tel", "order id", "Date"
                    }
                ));
                jTable11.setGridColor(new java.awt.Color(0, 204, 204));
                jTable11.setSelectionBackground(new java.awt.Color(0, 102, 102));
                jTable11.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable11MouseClicked(evt);
                    }
                });

                if (jTable11.getColumnModel().getColumnCount() > 0) {
                    jTable11.getColumnModel().getColumn(2).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(2).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(2).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(3).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(3).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(3).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(4).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(4).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(4).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(6).setMinWidth(65);
                    jTable11.getColumnModel().getColumn(6).setPreferredWidth(65);
                    jTable11.getColumnModel().getColumn(6).setMaxWidth(65);
                    jTable11.getColumnModel().getColumn(10).setMinWidth(0);
                    jTable11.getColumnModel().getColumn(10).setPreferredWidth(0);
                    jTable11.getColumnModel().getColumn(10).setMaxWidth(0);
                }

                
                Session session=null;
                session=HibernateUtil.getSessionFactory().openSession();
                final AtomicReference<ResultSet> order=new AtomicReference<>();
                session.doWork(connection->{
                    try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getoerdernew(?,?)}")){
                        cst.setInt(1, 0);
                        cst.setString(2, "pending");
                        cst.execute();
                        order.set(cst.getResultSet());
                        try(ResultSet rs =cst.getResultSet()){
                            while(rs.next()){

                                String name = rs.getString("item_name");
                                String catagory=rs.getString("item_catagory");
                                String price=rs.getString("item_price");
                                String quntity=rs.getString("neworder_quntity");
                                String username = rs.getString("user_full_name");
                                String usertg=rs.getString("user_reg");
                                String address=rs.getString("neworder_new_addres");
                                String deliver=rs.getString("deliver_name");
                                String delitel=rs.getString("deliver_tel");
                                String orderidre=rs.getString("neworder_id");
                                String adddate=rs.getString("neworder_date");
                                int totalint=(rs.getInt("item_price") * rs.getInt("neworder_quntity"));
                                String total = ""+totalint;


                                String tbData[] = {name, catagory, price, quntity, total, username, usertg, address, deliver, delitel, orderidre, adddate};
                                DefaultTableModel tblm = (DefaultTableModel) jTable11.getModel();
                                tblm.addRow(tbData);

                            }
                        }
                    }
                });
                
                selectitemid=null;
        }else{
            jLabel9.setForeground(new java.awt.Color(255, 0, 0));
            jLabel9.setText("Please Select Item !");
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        
        jLabel24.setVisible(true);
        jLabel23.setVisible(true);
        jLabel25.setVisible(true);
        jLabel9.setVisible(true);
        
        jTable11.setBackground(new java.awt.Color(0, 204, 204));
                jTable11.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Item Name", "Item Catagory", " Price", "Quntity", "Total", "User Name", "User Rg", "User Address", "Deliver", "Deliver Tel", "order id", "Date"
                    }
                ));
                jTable11.setGridColor(new java.awt.Color(0, 204, 204));
                jTable11.setSelectionBackground(new java.awt.Color(0, 102, 102));
                jTable11.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable11MouseClicked(evt);
                    }
                });

                if (jTable11.getColumnModel().getColumnCount() > 0) {
                    jTable11.getColumnModel().getColumn(2).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(2).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(2).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(3).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(3).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(3).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(4).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(4).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(4).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(6).setMinWidth(65);
                    jTable11.getColumnModel().getColumn(6).setPreferredWidth(65);
                    jTable11.getColumnModel().getColumn(6).setMaxWidth(65);
                    jTable11.getColumnModel().getColumn(10).setMinWidth(0);
                    jTable11.getColumnModel().getColumn(10).setPreferredWidth(0);
                    jTable11.getColumnModel().getColumn(10).setMaxWidth(0);
                }
                
                Session session=null;
                session=HibernateUtil.getSessionFactory().openSession();
                final AtomicReference<ResultSet> order=new AtomicReference<>();
                session.doWork(connection->{
                    try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getoerdernew(?,?)}")){
                        cst.setInt(1, 0);
                        cst.setString(2, "pending");
                        cst.execute();
                        order.set(cst.getResultSet());
                        try(ResultSet rs =cst.getResultSet()){
                            while(rs.next()){

                                String name = rs.getString("item_name");
                                String catagory=rs.getString("item_catagory");
                                String price=rs.getString("item_price");
                                String quntity=rs.getString("neworder_quntity");
                                String username = rs.getString("user_full_name");
                                String usertg=rs.getString("user_reg");
                                String address=rs.getString("neworder_new_addres");
                                String deliver=rs.getString("deliver_name");
                                String delitel=rs.getString("deliver_tel");
                                String orderidre=rs.getString("neworder_id");
                                String adddate=rs.getString("neworder_date");
                                int totalint=(rs.getInt("item_price") * rs.getInt("neworder_quntity"));
                                String total = ""+totalint;


                                String tbData[] = {name, catagory, price, quntity, total, username, usertg, address, deliver, delitel, orderidre, adddate};
                                DefaultTableModel tblm = (DefaultTableModel) jTable11.getModel();
                                tblm.addRow(tbData);

                            }
                        }
                    }
                });
                
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField1.setText("");
                jTextField2.setText("");

                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");

                jTextField9.setText("");
                jTextField10.setText("");

        
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jLabel25.setVisible(false);
        jLabel9.setVisible(false);
        
         jTable11.setBackground(new java.awt.Color(0, 204, 204));
                jTable11.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Item Name", "Item Catagory", " Price", "Quntity", "Total", "User Name", "User Rg", "User Address", "Deliver", "Deliver Tel", "order id", "Date"
                    }
                ));
                jTable11.setGridColor(new java.awt.Color(0, 204, 204));
                jTable11.setSelectionBackground(new java.awt.Color(0, 102, 102));
                jTable11.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable11MouseClicked(evt);
                    }
                });

                if (jTable11.getColumnModel().getColumnCount() > 0) {
                    jTable11.getColumnModel().getColumn(2).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(2).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(2).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(3).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(3).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(3).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(4).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(4).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(4).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(6).setMinWidth(65);
                    jTable11.getColumnModel().getColumn(6).setPreferredWidth(65);
                    jTable11.getColumnModel().getColumn(6).setMaxWidth(65);
                    jTable11.getColumnModel().getColumn(10).setMinWidth(0);
                    jTable11.getColumnModel().getColumn(10).setPreferredWidth(0);
                    jTable11.getColumnModel().getColumn(10).setMaxWidth(0);
                }
                
                Session session=null;
                session=HibernateUtil.getSessionFactory().openSession();
                final AtomicReference<ResultSet> order=new AtomicReference<>();
                session.doWork(connection->{
                    try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getoerdernew(?,?)}")){
                        cst.setInt(1, 0);
                        cst.setString(2, "Report");
                        cst.execute();
                        order.set(cst.getResultSet());
                        try(ResultSet rs =cst.getResultSet()){
                            while(rs.next()){

                                String name = rs.getString("item_name");
                                String catagory=rs.getString("item_catagory");
                                String price=rs.getString("item_price");
                                String quntity=rs.getString("neworder_quntity");
                                String username = rs.getString("user_full_name");
                                String usertg=rs.getString("user_reg");
                                String address=rs.getString("neworder_new_addres");
                                String deliver=rs.getString("deliver_name");
                                String delitel=rs.getString("deliver_tel");
                                String orderidre=rs.getString("neworder_id");
                                String adddate=rs.getString("neworder_date");
                                int totalint=(rs.getInt("item_price") * rs.getInt("neworder_quntity"));
                                String total = ""+totalint;


                                String tbData[] = {name, catagory, price, quntity, total, username, usertg, address, deliver, delitel, orderidre, adddate};
                                DefaultTableModel tblm = (DefaultTableModel) jTable11.getModel();
                                tblm.addRow(tbData);

                            }
                        }
                    }
                });
                
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField1.setText("");
                jTextField2.setText("");

                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");

                jTextField9.setText("");
                jTextField10.setText("");
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        
         
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jLabel25.setVisible(false);
        jLabel9.setVisible(false);
        
         jTable11.setBackground(new java.awt.Color(0, 204, 204));
                jTable11.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Item Name", "Item Catagory", " Price", "Quntity", "Total", "User Name", "User Rg", "User Address", "Deliver", "Deliver Tel", "order id", "Date"
                    }
                ));
                jTable11.setGridColor(new java.awt.Color(0, 204, 204));
                jTable11.setSelectionBackground(new java.awt.Color(0, 102, 102));
                jTable11.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable11MouseClicked(evt);
                    }
                });

                if (jTable11.getColumnModel().getColumnCount() > 0) {
                    jTable11.getColumnModel().getColumn(2).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(2).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(2).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(3).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(3).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(3).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(4).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(4).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(4).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(6).setMinWidth(65);
                    jTable11.getColumnModel().getColumn(6).setPreferredWidth(65);
                    jTable11.getColumnModel().getColumn(6).setMaxWidth(65);
                    jTable11.getColumnModel().getColumn(10).setMinWidth(0);
                    jTable11.getColumnModel().getColumn(10).setPreferredWidth(0);
                    jTable11.getColumnModel().getColumn(10).setMaxWidth(0);
                }
                
                Session session=null;
                session=HibernateUtil.getSessionFactory().openSession();
                final AtomicReference<ResultSet> order=new AtomicReference<>();
                session.doWork(connection->{
                    try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getoerdernew(?,?)}")){
                        cst.setInt(1, 0);
                        cst.setString(2, "Reseve");
                        cst.execute();
                        order.set(cst.getResultSet());
                        try(ResultSet rs =cst.getResultSet()){
                            while(rs.next()){

                                String name = rs.getString("item_name");
                                String catagory=rs.getString("item_catagory");
                                String price=rs.getString("item_price");
                                String quntity=rs.getString("neworder_quntity");
                                String username = rs.getString("user_full_name");
                                String usertg=rs.getString("user_reg");
                                String address=rs.getString("neworder_new_addres");
                                String deliver=rs.getString("deliver_name");
                                String delitel=rs.getString("deliver_tel");
                                String orderidre=rs.getString("neworder_id");
                                String adddate=rs.getString("neworder_date");
                                int totalint=(rs.getInt("item_price") * rs.getInt("neworder_quntity"));
                                String total = ""+totalint;


                                String tbData[] = {name, catagory, price, quntity, total, username, usertg, address, deliver, delitel, orderidre, adddate};
                                DefaultTableModel tblm = (DefaultTableModel) jTable11.getModel();
                                tblm.addRow(tbData);

                            }
                        }
                    }
                });
                
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField1.setText("");
                jTextField2.setText("");

                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");

                jTextField9.setText("");
                jTextField10.setText("");
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
           
        jLabel24.setVisible(false);
        jLabel23.setVisible(false);
        jLabel25.setVisible(false);
        jLabel9.setVisible(false);
        
         jTable11.setBackground(new java.awt.Color(0, 204, 204));
                jTable11.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Item Name", "Item Catagory", " Price", "Quntity", "Total", "User Name", "User Rg", "User Address", "Deliver", "Deliver Tel", "order id", "Date"
                    }
                ));
                jTable11.setGridColor(new java.awt.Color(0, 204, 204));
                jTable11.setSelectionBackground(new java.awt.Color(0, 102, 102));
                jTable11.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable11MouseClicked(evt);
                    }
                });

                if (jTable11.getColumnModel().getColumnCount() > 0) {
                    jTable11.getColumnModel().getColumn(2).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(2).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(2).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(3).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(3).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(3).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(4).setMinWidth(50);
                    jTable11.getColumnModel().getColumn(4).setPreferredWidth(50);
                    jTable11.getColumnModel().getColumn(4).setMaxWidth(50);
                    jTable11.getColumnModel().getColumn(6).setMinWidth(65);
                    jTable11.getColumnModel().getColumn(6).setPreferredWidth(65);
                    jTable11.getColumnModel().getColumn(6).setMaxWidth(65);
                    jTable11.getColumnModel().getColumn(10).setMinWidth(0);
                    jTable11.getColumnModel().getColumn(10).setPreferredWidth(0);
                    jTable11.getColumnModel().getColumn(10).setMaxWidth(0);
                }
                
                Session session=null;
                session=HibernateUtil.getSessionFactory().openSession();
                final AtomicReference<ResultSet> order=new AtomicReference<>();
                session.doWork(connection->{
                    try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getoerdernew(?,?)}")){
                        cst.setInt(1, 0);
                        cst.setString(2, "shipd");
                        cst.execute();
                        order.set(cst.getResultSet());
                        try(ResultSet rs =cst.getResultSet()){
                            while(rs.next()){

                                String name = rs.getString("item_name");
                                String catagory=rs.getString("item_catagory");
                                String price=rs.getString("item_price");
                                String quntity=rs.getString("neworder_quntity");
                                String username = rs.getString("user_full_name");
                                String usertg=rs.getString("user_reg");
                                String address=rs.getString("neworder_new_addres");
                                String deliver=rs.getString("deliver_name");
                                String delitel=rs.getString("deliver_tel");
                                String orderidre=rs.getString("neworder_id");
                                String adddate=rs.getString("neworder_date");
                                int totalint=(rs.getInt("item_price") * rs.getInt("neworder_quntity"));
                                String total = ""+totalint;


                                String tbData[] = {name, catagory, price, quntity, total, username, usertg, address, deliver, delitel, orderidre, adddate};
                                DefaultTableModel tblm = (DefaultTableModel) jTable11.getModel();
                                tblm.addRow(tbData);

                            }
                        }
                    }
                });
                
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField1.setText("");
                jTextField2.setText("");

                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");

                jTextField9.setText("");
                jTextField10.setText("");
    }//GEN-LAST:event_jLabel13MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable11;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
