/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import ClassSet.EmailSend;
import static UI.LogReg2.session3;
import com.mysql.jdbc.CallableStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.Transaction;
import pojo.Neworder;
import sesion.HibernateUtil;
import sesion.HibernateUtil1;

/**
 *
 * @author G I U S Chamika
 */
public class orderform extends javax.swing.JFrame {

    int orteritemid=0;
    int loguser=LogReg.Lloguserid;
    int itemprice=0;
    int itemquntinew=0;
    public orderform(int itemId) {
        initComponents();
        this.orteritemid=itemId;
        
            Session session=null;
            session=HibernateUtil1.getSessionFactory().openSession();
            final AtomicReference<ResultSet> item=new AtomicReference<>();
            session.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getitemdetails(?)}")){
                    cst.setInt(1, orteritemid);
                    cst.execute();
                    item.set(cst.getResultSet());
                    try(ResultSet rs =cst.getResultSet()){
                        while(rs.next()){
                            itemquntinew = rs.getInt("item_quntity");
                            if(itemquntinew==0){
                                jLabel7.setVisible(false);
                                jLabel390.setText("sorry No item !");
                            }
                            jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource(rs.getString("item_img"))));
                            jLabel9.setText(rs.getString("item_name")+"("+rs.getString("item_catagory")+")");
                            jLabel10.setText("Rs: "+rs.getInt("item_price")+"/-");
                            itemprice = rs.getInt("item_price");
                           jLabel389.setText("(One Unit) "+itemprice+"/-");
                        }
                    }
                }
            });
            
            Session session2=null;
            session2=HibernateUtil1.getSessionFactory().openSession();
            final AtomicReference<ResultSet> user=new AtomicReference<>();
            session2.doWork(connection->{
                try(CallableStatement cst2=(CallableStatement) connection.prepareCall("{call getusedata(?)}")){
                    cst2.setInt(1, loguser);
                    cst2.execute();
                    item.set(cst2.getResultSet());
                    try(ResultSet rs2 =cst2.getResultSet()){
                        while(rs2.next()){
                            jLabel14.setText(rs2.getString("user_full_name"));
                            jLabel13.setText(rs2.getString("user_reg"));
                            jLabel11.setText(rs2.getString("user_email"));
                            jTextField178.setText(rs2.getString("user_tel"));
                            jTextField289.setText(rs2.getString("user_addres"));
                        }
                    }
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField178 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField289 = new javax.swing.JTextField();
        jLabel390 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        error45 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel389 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(78, 148, 148));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 270, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 270, 10));

        jLabel11.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("sahanchamika@gam9ilcom");
        jLabel11.setFocusable(false);
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setIconTextGap(2);
        jLabel11.setInheritsPopupMenu(false);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 250, 20));

        jComboBox1.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox1.setMaximumRowCount(4);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 270, 20));

        jTextField178.setBackground(new java.awt.Color(121, 174, 171));
        jTextField178.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField178.setForeground(new java.awt.Color(102, 102, 102));
        jTextField178.setText("xxx-xxxxxxx");
        jTextField178.setBorder(null);
        jTextField178.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField178ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField178, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 143, 270, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enter3.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Telno:");
        jLabel17.setFocusable(false);
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel17.setIconTextGap(2);
        jLabel17.setInheritsPopupMenu(false);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 80, 20));

        jTextField289.setBackground(new java.awt.Color(121, 174, 171));
        jTextField289.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField289.setForeground(new java.awt.Color(102, 102, 102));
        jTextField289.setText("address");
        jTextField289.setBorder(null);
        jTextField289.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField289ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField289, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 213, 270, 20));

        jLabel390.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel390.setForeground(new java.awt.Color(255, 0, 0));
        jLabel390.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel390, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 250, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel btt.png"))); // NOI18N
        jLabel20.setText("jLabel7");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 90, 30));

        jLabel18.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Toatal price Rs:");
        jLabel18.setFocusable(false);
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel18.setIconTextGap(2);
        jLabel18.setInheritsPopupMenu(false);
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, 20));

        error45.setBackground(new java.awt.Color(0, 204, 204));
        error45.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        error45.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(error45, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 300, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/order btt.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 90, 30));

        jLabel389.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel389.setForeground(new java.awt.Color(255, 0, 0));
        jLabel389.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel389.setText("000");
        jPanel1.add(jLabel389, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 110, 20));

        jLabel19.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Address");
        jLabel19.setFocusable(false);
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19.setIconTextGap(2);
        jLabel19.setInheritsPopupMenu(false);
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 80, 20));

        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menulunchimg.png"))); // NOI18N
        jPanel1.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 120));

        jLabel16.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Quantity:");
        jLabel16.setFocusable(false);
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.setIconTextGap(2);
        jLabel16.setInheritsPopupMenu(false);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 80, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Lunch NOW Available");
        jLabel9.setFocusable(false);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setIconTextGap(2);
        jLabel9.setInheritsPopupMenu(false);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 230, 20));

        jLabel10.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Rs: 100.00");
        jLabel10.setFocusable(false);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setIconTextGap(2);
        jLabel10.setInheritsPopupMenu(false);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 170, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menulunchup.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 210));

        jLabel12.setFont(new java.awt.Font("Lucida Console", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Order User INfo:");
        jLabel12.setFocusable(false);
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setIconTextGap(2);
        jLabel12.setInheritsPopupMenu(false);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 290, 20));

        jLabel13.setFont(new java.awt.Font("Lucida Console", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("TG/2017/262");
        jLabel13.setFocusable(false);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setIconTextGap(2);
        jLabel13.setInheritsPopupMenu(false);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 250, 20));

        jLabel14.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("G I U S Chamika");
        jLabel14.setFocusable(false);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setIconTextGap(2);
        jLabel14.setInheritsPopupMenu(false);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orderuserdetails.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 310, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orderleftform.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 370, 400));

        jLabel15.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("G I U S Chamika");
        jLabel15.setFocusable(false);
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15.setIconTextGap(2);
        jLabel15.setInheritsPopupMenu(false);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 250, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField178ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField178ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField178ActionPerformed

    private void jTextField289ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField289ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField289ActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        
        this.setVisible(false);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int total=0;
        int selectquntity=(int) jComboBox1.getSelectedIndex();
        selectquntity=selectquntity+1;
        total=(selectquntity * itemprice);
        jLabel389.setText(total+"/-");
        
    }//GEN-LAST:event_jLabel4MouseClicked
    int deliverno=0;
    int todayquntity=0;
    static Session session4=null;
    //user register 
    public static void order(Neworder e){
        session4=HibernateUtil1.getSessionFactory().openSession();
        Transaction tx4=session4.beginTransaction();
        session4.save(e);
        tx4.commit();
        session4.close();
    }
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        String timenow=null;
        String datenow=null;
        int selectquntity2=(int) jComboBox1.getSelectedIndex();
        int selectq=(selectquntity2 + 1);
        String telno=jTextField178.getText();
        String address=jTextField289.getText();
        if(!telno.isEmpty() && !address.isEmpty() && !telno.equals("xxx-xxxxxxx") && !address.equals("address")){
            error45.setText("");
            Date thisDate=new Date();
            SimpleDateFormat hover=new SimpleDateFormat("hh mm a");
            timenow=hover.format(thisDate);
            SimpleDateFormat date=new SimpleDateFormat("Y-MM-dd");
            datenow=date.format(thisDate);
            
            Session session3=null;
            session3=HibernateUtil1.getSessionFactory().openSession();
            final AtomicReference<ResultSet> deliver=new AtomicReference<>();
            session3.doWork(connection->{
                try(CallableStatement cst3=(CallableStatement) connection.prepareCall("{call getdeliver()}")){
                    cst3.execute();
                    deliver.set(cst3.getResultSet());
                    try(ResultSet rs3 =cst3.getResultSet()){
                        while(rs3.next()){
                          deliverno =  rs3.getInt("deliver_id");
                          todayquntity = ( rs3.getInt("deliver_qun_today") + selectq);
                        }
                    }
                }
            });
            int response = JOptionPane.showConfirmDialog(this, "Conform Order","",JOptionPane.YES_NO_CANCEL_OPTION);
            if(response==JOptionPane.YES_OPTION){
             
                Neworder e=new Neworder(orteritemid, selectq, datenow, timenow, loguser, address, "pending", deliverno);
                order(e);
            Session session4=null;
            session4=HibernateUtil1.getSessionFactory().openSession();
            final AtomicReference<ResultSet> bill=new AtomicReference<>();
            session4.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call lastbilldata(?)}")){
                    cst.setInt(1, loguser);
                    cst.execute();
                    bill.set(cst.getResultSet());
                    try(ResultSet rs =cst.getResultSet()){
                        while(rs.next()){
                            String fulname=rs.getString("user_full_name");
                            String userreg="("+rs.getString("user_reg")+")";
                            String itemname=rs.getString("item_name");
                            String price="RS: "+rs.getInt("item_price")+"/-";
                            String quntity=rs.getInt("neworder_quntity")+" Item";
                            String addr=rs.getString("neworder_new_addres");
                            String email3=rs.getString("user_email");
                            String dname=rs.getString("deliver_name");
                            String dtel=rs.getString("deliver_tel");
                            int price2 =rs.getInt("item_price");
                            int qun =rs.getInt("neworder_quntity");
                            int Total2 = (price2 * qun);
                            
                            //send otp email
                            EmailSend es=new EmailSend();
                            es.SendMail("<b>New Bill</b> <br> User--> "+fulname+" "+userreg+" <br> Item--> "+itemname+" <br> Price--> "+price+" <br> Quantity--> "+quntity+" <br> Order Address--> "+addr+" <br> Deliver--> "+dname+" <br> Deliver telNo:--> "+dtel+" <br> Total--> RS:"+Total2+"/- <br> <b>Thank you! <br> Use Our System Again</b>",email3,"Fot Canteen Online Food Ordering System New Order Bill");
                            
                            
                        }
                    }
                }
            });
            int uptotqun=(itemquntinew - selectq);
            Session session5=null;
            session5=HibernateUtil1.getSessionFactory().openSession();
            final AtomicReference<ResultSet> item=new AtomicReference<>();
            session5.doWork(connection->{
                try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call upitemqun(?,?)}")){
                    cst.setInt(1, uptotqun);
                    cst.setInt(2, orteritemid);
                    cst.execute();
                    
                }
            });
            
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, "Order Successfull!");
            }
            //System.out.println(orteritemid);
            
        }else{
            error45.setText("Some field/s Empty !");
        }
        
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderform(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error45;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel389;
    private javax.swing.JLabel jLabel390;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField178;
    private javax.swing.JTextField jTextField289;
    // End of variables declaration//GEN-END:variables
}
