/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import ClassSet.EmailSend;
import static UI.LogReg2.isValid;
import com.mysql.jdbc.CallableStatement;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.Iterator;
import java.util.Random;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import pojo.User;
import sesion.HibernateUtil;
import sesion.HibernateUtil1;

/**
 *
 * @author G I U S Chamika
 */
public class Profile extends javax.swing.JInternalFrame {

   int loguser=LogReg.Lloguserid;
   
    public Profile() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
        
        Session session=null;
        session=HibernateUtil1.getSessionFactory().openSession();
        final AtomicReference<ResultSet> itemid=new AtomicReference<>();
        session.doWork(connection->{
            try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call getusedata(?)}")){
                cst.setInt(1, loguser);
                cst.execute();
                itemid.set(cst.getResultSet());
                try(ResultSet rs =cst.getResultSet()){
                    while(rs.next()){
                        String fname=rs.getString("user_full_name");
                        jLabel7.setText(fname);
                        String regno=rs.getString("user_reg");
                        jLabel4.setText(regno);
                        String email=rs.getString("user_email");
                        jLabel6.setText(email);
                        editemail5.setText(email);
                        String tno=rs.getString("user_tel");
                        jLabel5.setText(tno);
                        edittel.setText(tno);
                        String un=rs.getString("user_name");
                        fnamer.setText(un);
                        unameedit.setText(un);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fnamer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        eroorlod56 = new javax.swing.JLabel();
        unameedit = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        edittel = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        editemail5 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        eroorlod5 = new javax.swing.JLabel();
        passc1 = new javax.swing.JPasswordField();
        passw2 = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fnamer1uyi = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        eroorlod3 = new javax.swing.JLabel();
        eroorlod4 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(819, 526));
        setPreferredSize(new java.awt.Dimension(819, 526));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Change Profile pic");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 40, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Console", 1, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Username");
        jLabel7.setFocusable(false);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setIconTextGap(2);
        jLabel7.setInheritsPopupMenu(false);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 270, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email@gmail.com");
        jLabel6.setFocusable(false);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setIconTextGap(2);
        jLabel6.setInheritsPopupMenu(false);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("0770609547");
        jLabel5.setFocusable(false);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setIconTextGap(2);
        jLabel5.setInheritsPopupMenu(false);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 270, 20));

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TG/2017/262");
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setIconTextGap(2);
        jLabel4.setInheritsPopupMenu(false);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 270, 30));

        fnamer.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        fnamer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fnamer.setText("G I U S Chamika");
        fnamer.setFocusable(false);
        fnamer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fnamer.setIconTextGap(2);
        fnamer.setInheritsPopupMenu(false);
        jPanel2.add(fnamer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/male_user.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 118, 108));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userdetails.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 460));

        jLayeredPane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 320, -1));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eroorlod56.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        eroorlod56.setForeground(new java.awt.Color(255, 51, 0));
        eroorlod56.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eroorlod56.setFocusable(false);
        eroorlod56.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eroorlod56.setIconTextGap(2);
        eroorlod56.setInheritsPopupMenu(false);
        jPanel4.add(eroorlod56, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 380, 10));

        unameedit.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        unameedit.setForeground(new java.awt.Color(204, 204, 204));
        unameedit.setText("Enter Username");
        unameedit.setBorder(null);
        unameedit.setOpaque(false);
        unameedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameeditActionPerformed(evt);
            }
        });
        jPanel4.add(unameedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 350, 30));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 340, 10));

        jLabel12.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("TelNo :");
        jLabel12.setFocusable(false);
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setIconTextGap(2);
        jLabel12.setInheritsPopupMenu(false);
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 110, 20));

        jLabel13.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Password (New):");
        jLabel13.setFocusable(false);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setIconTextGap(2);
        jLabel13.setInheritsPopupMenu(false);
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 120, 20));

        jLabel14.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Password (commform):");
        jLabel14.setFocusable(false);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setIconTextGap(2);
        jLabel14.setInheritsPopupMenu(false);
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 230, 20));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 340, 10));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 340, 10));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/submit.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 30, 30));

        edittel.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        edittel.setForeground(new java.awt.Color(204, 204, 204));
        edittel.setText("xxx-xxxxxxx");
        edittel.setBorder(null);
        edittel.setOpaque(false);
        edittel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edittelActionPerformed(evt);
            }
        });
        jPanel4.add(edittel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 350, 30));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 340, 10));

        jLabel16.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Email :");
        jLabel16.setFocusable(false);
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.setIconTextGap(2);
        jLabel16.setInheritsPopupMenu(false);
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 120, 20));

        editemail5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        editemail5.setForeground(new java.awt.Color(204, 204, 204));
        editemail5.setText("Email@.com");
        editemail5.setBorder(null);
        editemail5.setOpaque(false);
        editemail5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editemail5ActionPerformed(evt);
            }
        });
        jPanel4.add(editemail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 350, 20));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 340, 10));

        eroorlod5.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        eroorlod5.setForeground(new java.awt.Color(51, 204, 0));
        eroorlod5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eroorlod5.setFocusable(false);
        eroorlod5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eroorlod5.setIconTextGap(2);
        eroorlod5.setInheritsPopupMenu(false);
        jPanel4.add(eroorlod5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 370, 10));

        passc1.setForeground(new java.awt.Color(204, 204, 204));
        passc1.setBorder(null);
        jPanel4.add(passc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 340, 10));

        passw2.setForeground(new java.awt.Color(204, 204, 204));
        passw2.setBorder(null);
        jPanel4.add(passw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 340, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("User name :");
        jLabel18.setFocusable(false);
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel18.setIconTextGap(2);
        jLabel18.setInheritsPopupMenu(false);
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/submit.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/submit.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 30, 30));

        fnamer1uyi.setBackground(new java.awt.Color(51, 255, 204));
        fnamer1uyi.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        fnamer1uyi.setForeground(new java.awt.Color(0, 204, 204));
        fnamer1uyi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fnamer1uyi.setText("Update User Details");
        fnamer1uyi.setFocusable(false);
        fnamer1uyi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fnamer1uyi.setIconTextGap(2);
        fnamer1uyi.setInheritsPopupMenu(false);
        jPanel4.add(fnamer1uyi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 270, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edituser.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 470));

        eroorlod3.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        eroorlod3.setForeground(new java.awt.Color(255, 51, 51));
        eroorlod3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eroorlod3.setFocusable(false);
        eroorlod3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eroorlod3.setIconTextGap(2);
        eroorlod3.setInheritsPopupMenu(false);
        jPanel4.add(eroorlod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 360, 10));

        eroorlod4.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        eroorlod4.setForeground(new java.awt.Color(255, 51, 51));
        eroorlod4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eroorlod4.setFocusable(false);
        eroorlod4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eroorlod4.setIconTextGap(2);
        eroorlod4.setInheritsPopupMenu(false);
        jPanel4.add(eroorlod4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 360, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unameeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameeditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameeditActionPerformed

    private void edittelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edittelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edittelActionPerformed

    private void editemail5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editemail5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editemail5ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Session session2 =null;
        String upun=unameedit.getText();
        String uptel=edittel.getText();
        if(upun.isEmpty() && uptel.isEmpty()){
            eroorlod56.setText("Both of Fields empty Not Update !");
        }else{
            if(!upun.isEmpty()){
               if(!uptel.isEmpty()){
                    String regex="\\d{3}-\\d{7}";
                    if(uptel.matches(regex)==true && !uptel.equals("000-0000000")){ 
                        int unupstate=0;
                        //username an regNo validate
                         session2=HibernateUtil1.getSessionFactory().openSession();
                         Transaction tx2=session2.beginTransaction();
                         String user_sql="FROM User";
                         Query user_quary=session2.createQuery(user_sql);

                         java.util.List <User>userList=user_quary.list();
                           for(Iterator<User> userIterator=userList.iterator();userIterator.hasNext();){
                            User user=userIterator.next();

                               if (!user.getUserName().equals(upun)){


                               }else{
                                   unupstate=1;
                               }
                            }
                         if(unupstate==1){
                             eroorlod56.setText("Sorry User name Already use !");
                             eroorlod5.setText("");
                         }else{
                             Session session3=null;
                             session3=HibernateUtil1.getSessionFactory().openSession();
                             final AtomicReference<ResultSet> itemid=new AtomicReference<>();
                             session3.doWork(connection->{
                                  try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call updateud1(?,?,?)}")){
                                      cst.setInt(1, loguser);
                                      cst.setString(2, upun); 
                                      cst.setString(3, uptel);
                                      cst.execute();
                                      eroorlod5.setText("Update Successful..");
                                      eroorlod56.setText("");
                                  }
                              });
                         }
                    }else{
                        eroorlod56.setText("Invalid Tel NO !");
                        eroorlod5.setText("");
                    } 
                }else{
                    eroorlod56.setText("User Tel NO is empty Not Update !");
                    eroorlod5.setText("");
                } 
            }else{
                eroorlod56.setText("User name is empty Not Update !");
                eroorlod5.setText("");
            }
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        
        String pass=passc1.getText();
        String passc=passw2.getText();
        
        if(!pass.isEmpty() && !passc.isEmpty()){
            String pattern = "(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}";
            boolean pwdval1=pass.matches(pattern);
            boolean pwdval2=passc.matches(pattern);
            if (pwdval1 == true && pwdval2 == true){
                if (pass.equals(passc)){
                    //encrip pwd
                    String generatedPassword2 = null;
                        try {

                            MessageDigest md = MessageDigest.getInstance("MD5");
                            md.update(pass.getBytes());
                            byte[] bytes = md.digest();
                            StringBuilder sb = new StringBuilder();
                            for(int i=0; i< bytes.length ;i++){
                                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
                            }
                            generatedPassword2 = sb.toString();
                        } 
                           catch (NoSuchAlgorithmException e) 
                        {
                            e.printStackTrace();
                        }
                           
                            Session session4=null;
                            session4=HibernateUtil1.getSessionFactory().openSession();
                            Transaction tx=session4.beginTransaction();
                            String reglist_sql="FROM User";
                            Query reglist_quary=session4.createQuery(reglist_sql);

                            java.util.List <User>regNumList=reglist_quary.list();
                            for(Iterator<User> regIterator=regNumList.iterator();regIterator.hasNext();){
                                User user=regIterator.next();

                                if(user.getUserId()== loguser){
                                        
                                        user.setUserPassword(generatedPassword2);
                                        session4.save(user);
                                        tx.commit();
                                        session4.close();

                                       eroorlod56.setText("");
                                       eroorlod5.setText("Password update Successful");
                                }
                            }        
                            
                }else{
                    eroorlod56.setText("conform password is incorect !");
                    eroorlod5.setText("");
                }        
            }else{
                eroorlod56.setText("Password Invalid (set srtong one) !");
                eroorlod5.setText("");
            }                
        }else{
            eroorlod56.setText("Field/s Empty fill two password fields !");
            eroorlod5.setText("");
        }
        
    }//GEN-LAST:event_jLabel17MouseClicked

    //email validate
    static boolean isValid(String email) {
      String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
      return email.matches(regex);
    }

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        
        String email=editemail5.getText();
        int mainstate=0;
        if(!email.isEmpty()){
            //validate email
            boolean frt=true;                   
            if (frt == isValid(email)){
                //otp maker
                String otp2= new DecimalFormat("000000").format(new Random().nextInt(999999));
                
                Session session5=null;
                session5=HibernateUtil1.getSessionFactory().openSession();
                final AtomicReference<ResultSet> itemid=new AtomicReference<>();
                session5.doWork(connection->{
                  try(CallableStatement cst=(CallableStatement) connection.prepareCall("{call upotp(?,?)}")){
                    cst.setInt(1, loguser);
                    cst.setString(2, otp2); 
                    cst.execute();
                    
                    //send otp email
                    EmailSend es=new EmailSend();
                    es.SendMail("Register Otp ---> "+otp2,email,"Fot Canteen Online Food Ordering System Register");
                    
                    new upemailotpvali(loguser,email).setVisible(true);
                  }
                });                                                                   
                
            }else{
                eroorlod56.setText("Invalid Email !");
                eroorlod5.setText("");
            }
        }else{
            eroorlod56.setText("Fields Empty fill email Fields !");
            eroorlod5.setText("");
        }
        
    }//GEN-LAST:event_jLabel15MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editemail5;
    private javax.swing.JTextField edittel;
    private javax.swing.JLabel eroorlod3;
    private javax.swing.JLabel eroorlod4;
    private javax.swing.JLabel eroorlod5;
    private javax.swing.JLabel eroorlod56;
    private javax.swing.JLabel fnamer;
    private javax.swing.JLabel fnamer1uyi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPasswordField passc1;
    private javax.swing.JPasswordField passw2;
    private javax.swing.JTextField unameedit;
    // End of variables declaration//GEN-END:variables
}
